language: python
python:
    - "3.5"
before_install:
    - sudo apt-get update 
    - sudo apt-get install -y poppler-utils
install: "pip install -r requirements.txt"
script: 
- flake8
- python -m unittest tests/*.py