language: python
python:
  - "3.5"
  - "3.4"
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y poppler-utils
  - git clone https://github.com/ONSdigital/sdx-common.git
  - pip3 install ./sdx-common
install: make build
script: make test
