steps:
- id: 'Unit Tests'
  name: 'eu.gcr.io/ons-sdx-ci/sdx-gcp:1.3.2'
  script: |
    #!/usr/bin/env bash
    apt-get update
    apt-get install -y poppler-utils
    pip install -r requirements.txt
    pip install -r test-requirements.txt
    pytest -v --cov-report term-missing --disable-warnings --cov=transform tests/
