steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - 'x=${PROJECT_ID}'
    id: Build Image
    script: |
      #!/usr/bin/env bash
      version=$(cat .version)
      echo ${version}
      docker build -t eu.gcr.io/${x}/sdx-transform .
      docker tag eu.gcr.io/${x}/sdx-transform:latest eu.gcr.io/${x}/sdx-transform:${version}
      docker push eu.gcr.io/${x}/sdx-transform:${version}
      docker push eu.gcr.io/${x}/sdx-transform:latest
