openapi: 3.0.2

info:
  title: sdx-transform-cs
  description: A service for transforming Survey Data Exchange (SDX) Surveys to formats in use in Common Software.
  version: "3.18.0"

servers:
  - url: http://localhost:8083/

paths:
  /healthcheck:
    get:
      summary: Healthcheck.
      description: Simple endpoint that reports the health of the application.
      responses:
        200:
          description: Healthcheck retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'
  /info:
    $ref: '#/paths/~1health'

  /pck:
    post:
      summary: Convert to pck format.
      description: Converts the supplied survey response into pck format.
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Pck'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'
  /pck/{batch_number}:
    post:
      summary: Convert to pck format.
      description: Converts the supplied survey response into pck format.
      parameters:
        - $ref: '#/components/parameters/BatchNumber'
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Pck'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /idbr:
    post:
      summary: Convert to idbr format.
      description: Converts the supplied survey response into idbr format.
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Idbr'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /images:
    post:
      summary: Convert to images in jpg format.
      description: Returns a zip file containing the response in jpg format and a csv describing the order of the images.
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Zip'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /common-software:
    post:
      summary: Convert to a zip of required files for Common Software.
      description: Returns a zip file containing a number files required by Common Software, including images, receipts, and the data in json and pck formats.
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Zip'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'
  /common-software/{sequence_no}:
    post:
      summary: Convert to a zip of required files for Common Software.
      description: Returns a zip file containing a number files required by Common Software, including images, receipts, and the data in json and pck formats.
      parameters:
        - $ref: '#/components/parameters/SequenceNumber'
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Zip'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'
  /common-software/{sequence_no}/{batch_number}:
    post:
      summary: Convert to a zip of required files for Common Software.
      description: Returns a zip file containing a number files required by Common Software, including images, receipts, and the data in json and pck formats.
      parameters:
        - $ref: '#/components/parameters/SequenceNumber'
        - $ref: '#/components/parameters/BatchNumber'
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Zip'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /cora:
    post:
      summary: Convert to a zip of required files for CORA.
      description: Returns a zip file containing a number files required by CORA, including images, receipts, and the data in json and colon seperated formats.
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Zip'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'
  /cora/{sequence_no}:
    post:
      summary: Convert to a zip of required files for CORA.
      description: Returns a zip file containing a number files required by CORA, including images, receipts, and the data in json and colon seperated formats.
      parameters:
        - $ref: '#/components/parameters/SequenceNumber'
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Zip'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /cord:
    post:
      summary: Convert to a zip of required files for CORD.
      description: Returns a zip file containing a number files required by CORD, including images, receipts, and the data in json and colon seperated formats.
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Zip'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'
  /cord/{sequence_no}:
    post:
      summary: Convert to a zip of required files for CORD.
      description: Returns a zip file containing a number files required by CORD, including images, receipts, and the data in json and colon seperated formats.
      parameters:
        - $ref: '#/components/parameters/SequenceNumber'
      requestBody:
        $ref: '#/components/requestBodies/SurveyResponse'
      responses:
        200:
          $ref: '#/components/responses/Zip'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'


components:
  parameters:
    SequenceNumber:
      name: sequence_no
      description: Sequence number
      in: path
      required: true
      schema:
        type: integer
        example: 0
    BatchNumber:
      name: batch_number
      description: Batch number
      in: path
      required: true
      schema:
        type: integer
        example: 0
  responses:
    ClientError:
      description: Client error
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              message:
                type: string
                example: "CORA survey with survey id 023 is not supported"
              uri:
                type: string
                example: "http://localhost:8083/cora"

    ServerError:
      description: Server error.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              message:
                type: string
                example: "Internal server error ..."

    Pck:
      description: Returned pck.
      content:
        text/html:
          schema:
            type: string
            example: "FV
                      RSI7B:12345678901A:0216
                      0001 00000000002
                      0011 00000010416
                      0012 00000311016
                      0020 00001800000
                      0146 00000000001"

    Idbr:
      description: Returned idbr.
      content:
        text/html:
          schema:
            type: string
            example: "12345678901:A:023:200216"

    Zip:
      description: Returned zip.
      content:
        application/zip:
          schema:
            type: string
            format: binary

  requestBodies:
    SurveyResponse:
      description: survey response
      content:
        application/json:
          schema:
            type: object
            properties:
              type:
                type: string
                example: "uk.gov.ons.edc.eq:surveyresponse"
              origin:
                type: string
                example: "uk.gov.ons.edc.eq"
              survey_id:
                type: string
                example: "023"
              version:
                type: string
                example: "0.0.1"
              collection:
                type: object
                properties:
                  exercise_sid:
                    type: string
                    example: "hfjdskf"
                  instrument_id:
                    type: string
                    example: "0203"
                  period:
                    type: string
                    example: "0216"
              submitted_at:
                type: string
                example: "2016-03-12T10:39:40Z"
              metadata:
                type: object
                properties:
                  user_id:
                    type: string
                    example: "789473423"
                  ru_ref:
                    type: string
                    example: "12345678901A"
              data:
                type: object
                example: '"11": "01/04/2016",
                          "12": "31/10/2016",
                          "20": "1800000",
                          "51": "84",
                          "146": "some comment"'
