apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdx-transform
  labels:
    app: sdx-transform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdx-transform
  template:
    metadata:
      labels:
        app: sdx-transform
    spec:
      containers:
      - image: eu.gcr.io/{{ .Values.registry_location }}/sdx-transform:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        name: sdx-transform
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 3
      serviceAccountName: sdx-workload-identity
